In [42]:
import pandas as pd
lit=pd.read_excel('lithium decay rate.xlsx')
lit

   lithium Decay Rate      Unnamed: 1
0           Haif Life  Decay Constant
1                0.84           0.825
2                0.85        0.815294
3                0.86        0.805814
4                0.87        0.796552
5                0.88          0.7875
6                0.89        0.778652
7                 0.9            0.77
8                0.91        0.761538
9                0.92        0.753261
10               0.93        0.745161
11               0.94        0.737234
12               0.95        0.729474
13               0.96        0.721875
14               0.97        0.714433
15               0.98        0.707143
16               0.99             0.7
17                  1           0.693

In [43]:
lit.rename(columns={'lithium Decay Rate':'Haif Life','Unnamed: 1':'Decay Constant'},inplace=True)

In [44]:
lit

    Haif Life  Decay Constant
0   Haif Life  Decay Constant
1        0.84           0.825
2        0.85        0.815294
3        0.86        0.805814
4        0.87        0.796552
5        0.88          0.7875
6        0.89        0.778652
7         0.9            0.77
8        0.91        0.761538
9        0.92        0.753261
10       0.93        0.745161
11       0.94        0.737234
12       0.95        0.729474
13       0.96        0.721875
14       0.97        0.714433
15       0.98        0.707143
16       0.99             0.7
17          1           0.693

In [45]:
lit2=lit.drop(0)

In [46]:
lit2

   Haif Life Decay Constant
1       0.84          0.825
2       0.85       0.815294
3       0.86       0.805814
4       0.87       0.796552
5       0.88         0.7875
6       0.89       0.778652
7        0.9           0.77
8       0.91       0.761538
9       0.92       0.753261
10      0.93       0.745161
11      0.94       0.737234
12      0.95       0.729474
13      0.96       0.721875
14      0.97       0.714433
15      0.98       0.707143
16      0.99            0.7
17         1          0.693

In [47]:
lit2.dtypes

Haif Life         object
Decay Constant    object
dtype: object

In [48]:
lit2

   Haif Life Decay Constant
1       0.84          0.825
2       0.85       0.815294
3       0.86       0.805814
4       0.87       0.796552
5       0.88         0.7875
6       0.89       0.778652
7        0.9           0.77
8       0.91       0.761538
9       0.92       0.753261
10      0.93       0.745161
11      0.94       0.737234
12      0.95       0.729474
13      0.96       0.721875
14      0.97       0.714433
15      0.98       0.707143
16      0.99            0.7
17         1          0.693

In [66]:
x=lit2[['Decay Constant']]

In [67]:
y=lit2['Haif Life']

In [68]:
from sklearn.model_selection import train_test_split

In [69]:
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.6,random_state=0)

In [70]:
from sklearn.linear_model import LinearRegression

In [71]:
model= LinearRegression().fit(x_train,y_train)

In [73]:
model.predict(x_test).round(3)

array([0.849, 0.903, 0.923, 0.933, 0.97 , 0.882, 0.86 , 0.978, 0.942,
       0.913, 0.995])

In [74]:
y_test

2     0.85
7      0.9
9     0.92
10    0.93
14    0.97
5     0.88
3     0.86
15    0.98
11    0.94
8     0.91
17       1
Name: Haif Life, dtype: object

In [82]:
prediction=model.predict(x_test).round(4)

In [83]:
from sklearn.metrics import r2_score
r2_score(prediction, y_test)*100

99.68545069373648